from pathlib import Path
import runpy


def test_release_identity_ignores_editable_install_metadata_but_tracks_payload(tmp_path):
    identity = runpy.run_path(str(Path(__file__).parents[1]/"system/source-id.py"))["source_id"]
    for name in ["pyproject.toml","uv.lock","config.yaml","data-schema.json","README.md","LICENSE"]:
        (tmp_path/name).write_text(name)
    source = tmp_path/"src/toddlerbox"
    source.mkdir(parents=True)
    (source/"app.py").write_text("original")
    original = identity(tmp_path)
    metadata = tmp_path/"src/ToddlerBox.egg-info"
    metadata.mkdir()
    (metadata/"SOURCES.txt").write_text("generated by uv sync")
    assert identity(tmp_path) == original
    (metadata/"SOURCES.txt").write_text("regenerated after tests")
    assert identity(tmp_path) == original
    (source/"app.py").write_text("changed behavior")
    assert identity(tmp_path) != original
    code_id = identity(tmp_path)
    (tmp_path/"LICENSE").write_text("changed bundled notice")
    assert identity(tmp_path) != code_id
